dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  image_picker: ^1.0.7
  google_fonts: ^6.1.0
  lucide_icons: ^0.3.0 # Or use material_design_icons_flutter
  cached_network_image: ^3.3.1 # For product images
