name: styfi
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase Core Dependencies
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  
  # Networking
  http: ^1.2.0
  
  # UI & Media
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  google_fonts: ^6.1.0

  # Icon
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
